---
# tasks file for timescaledb
- name: Stop Zabbix Server
  remote_user: root
  become: true
  systemd:
    name: zabbix-server
    state: stopped

- name: Add TimescaleDb Repo
  remote_user: root
  become: true
  shell: |
    tee /etc/yum.repos.d/timescale_timescaledb.repo <<EOL
    [timescale_timescaledb]
    name=timescale_timescaledb
    baseurl=https://packagecloud.io/timescale/timescaledb/el/$(rpm -E %{rhel})/\$basearch
    repo_gpgcheck=1
    gpgcheck=0
    enabled=1
    gpgkey=https://packagecloud.io/timescale/timescaledb/gpgkey
    sslverify=1
    sslcacert=/etc/pki/tls/certs/ca-bundle.crt
    metadata_expire=300
    EOL
  any_errors_fatal: true


- name: Install TimescaleDB 
  remote_user: root
  become: true
  shell: |
    dnf -y install timescaledb-2-postgresql-15
    timescaledb-tune --pg-config=/usr/pgsql-15/bin/pg_config -yes
    
- name: Create TimescaleDB Extention for PostgreSQL
  remote_user: root
  become: true
  shell:  |
    # echo "shared_preload_libraries = 'timescaledb'" >> /var/lib/pgsql/15/data/postgresql.conf
    systemctl restart postgresql-15.service
    echo "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;" | sudo -u postgres psql $DB_NAME
    cat /usr/share/doc/zabbix-sql-scripts/postgresql/timescaledb.sql | sudo -u $DB_USER psql $DB_NAME
  args:
    creates: "/usr/share/doc/zabbix-sql-scripts/postgresql/timescaledb.sql"
     


- name: Start Zabbix-Server
  systemd:
    name: zabbix-server
    state: started


