---

- name: Install Zabbix Repository
  remote_user: root
  become: true
  shell: |
    rpm -Uvh https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm
    dnf clean all
  any_errors_fatal: true


- name: Switch to PHP 7.4
  remote_user: root
  become: true
  shell: |
    dnf -y module switch-to php:7.4
  any_errors_fatal: true


- name: Install Zabbix server, frontend, agent
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - zabbix-server-pgsql
    - zabbix-web-pgsql
    - zabbix-nginx-conf
    - zabbix-sql-scripts
    - zabbix-selinux-policy
    - zabbix-agent


- name: Configuring Service Scripts
  copy:
    src: files/
    dest: /root/zabbix-scripts
    mode: '0755'



- name: Export DB envars and Set Up Database
  remote_user: root
  become: true
  shell: |
    cd /root/zabbix-scripts
    chmod +x envars.sh && ./envars.sh
    ./create_db.sh
    zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u $DB_USER psql $DB_NAME
  any_errors_fatal: true

- name: Copy Zabbix-Nginx configuration file
  template:
    src: nginx-zabbix.template
    dest: /etc/nginx/conf.d/zabbix.conf
  notify:
    - restart_nginx

- name: Copy Zabbix configuration file
  template:
    src: zabbix-server-conf.template
    dest: /etc/zabbix/zabbix_server.conf

- name: replace_env_vars
  remote_user: root
  become: true
  shell: |
    cd /root/zabbix-scripts
    chmod +x replace_env_vars.sh
    ./replace_env_vars.sh
  any_errors_fatal: true
  
- name: restart_zabbix
  service:
    name: zabbix-server
    state: restarted

- name: restart_nginx
  service:
    name: nginx
    state: restarted
  
- name: permit traffic in default zone on port 8081/tcp
  ansible.posix.firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
  
- name: permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled


